/**
 * Curated high-quality popular games database for fallback when RAWG API fails.
 * All games have official Steam CDN images, verified metacritic scores, ratings, and genre tags.
 */

export const FALLBACK_GAMES = [
  {
    id: 'rawg_4704690',
    rawgId: 4704690,
    rawgSlug: 'meccha-chameleon',
    name: 'Meccha Chameleon',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4704690/163e2a742e5fb8e1f5d1e3a890da98f04ab809d4/header.jpg?t=1781108224',
    metacritic: null,
    reviewScore: 92,
    totalReviews: 1050,
    isFree: false,
    genres: ['Gizlilik', 'Parti', 'Aksiyon'],
    released: '2026-06-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_4656000',
    rawgId: 4656000,
    rawgSlug: 'bombanana',
    name: 'BOMBANANA!',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4656000/99c086faba625a8d3bc459bab444087d257ccbe1/header.jpg?t=1783021639',
    metacritic: null,
    reviewScore: 0,
    totalReviews: 0,
    isFree: false,
    genres: ['Basit Eğlence', 'Bağımsız Yapım'],
    released: '2026-08-01',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  // Aksiyon & Macera & RPG
  {
    id: 'rawg_1245620',
    rawgId: 1245620,
    rawgSlug: 'elden-ring',
    name: 'Elden Ring',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
    metacritic: 96,
    reviewScore: 95,
    totalReviews: 642000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Macera'],
    released: '2022-02-25',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_271590',
    rawgId: 271590,
    rawgSlug: 'grand-theft-auto-v',
    name: 'Grand Theft Auto V',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
    metacritic: 96,
    reviewScore: 92,
    totalReviews: 1650000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2013-09-17',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1174180',
    rawgId: 1174180,
    rawgSlug: 'red-dead-redemption-2',
    name: 'Red Dead Redemption 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
    metacritic: 97,
    reviewScore: 93,
    totalReviews: 531000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2018-10-26',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1086940',
    rawgId: 1086940,
    rawgSlug: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg',
    metacritic: 96,
    reviewScore: 96,
    totalReviews: 580000,
    isFree: false,
    genres: ['RPG', 'Strateji', 'Macera'],
    released: '2023-08-03',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_292030',
    rawgId: 292030,
    rawgSlug: 'the-witcher-3-wild-hunt',
    name: 'The Witcher 3: Wild Hunt',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
    metacritic: 93,
    reviewScore: 96,
    totalReviews: 712000,
    isFree: false,
    genres: ['RPG', 'Aksiyon', 'Macera'],
    released: '2015-05-18',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1145360',
    rawgId: 1145360,
    rawgSlug: 'hades',
    name: 'Hades',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg',
    metacritic: 93,
    reviewScore: 98,
    totalReviews: 235000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Bağımsız'],
    released: '2020-09-17',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1091500',
    rawgId: 1091500,
    rawgSlug: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
    metacritic: 86,
    reviewScore: 80,
    totalReviews: 680000,
    isFree: false,
    genres: ['RPG', 'Aksiyon', 'Nişancı'],
    released: '2020-12-10',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1593500',
    rawgId: 1593500,
    rawgSlug: 'god-of-war',
    name: 'God of War',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg',
    metacritic: 93,
    reviewScore: 96,
    totalReviews: 92000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2022-01-14',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_367520',
    rawgId: 367520,
    rawgSlug: 'hollow-knight',
    name: 'Hollow Knight',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
    metacritic: 90,
    reviewScore: 97,
    totalReviews: 310000,
    isFree: false,
    genres: ['Platform', 'Aksiyon', 'Bağımsız'],
    released: '2017-02-24',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_504230',
    rawgId: 504230,
    rawgSlug: 'celeste',
    name: 'Celeste',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg',
    metacritic: 94,
    reviewScore: 97,
    totalReviews: 82000,
    isFree: false,
    genres: ['Platform', 'Macera', 'Bağımsız'],
    released: '2018-01-25',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_620',
    rawgId: 620,
    rawgSlug: 'portal-2',
    name: 'Portal 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/header.jpg',
    metacritic: 95,
    reviewScore: 99,
    totalReviews: 320000,
    isFree: false,
    genres: ['Bulmaca', 'Aksiyon', 'Platform'],
    released: '2011-04-18',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_400',
    rawgId: 400,
    rawgSlug: 'portal',
    name: 'Portal',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/400/header.jpg',
    metacritic: 90,
    reviewScore: 98,
    totalReviews: 120000,
    isFree: false,
    genres: ['Bulmaca', 'Aksiyon', 'Platform'],
    released: '2007-10-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_632470',
    rawgId: 632470,
    rawgSlug: 'disco-elysium',
    name: 'Disco Elysium',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/header.jpg',
    metacritic: 97,
    reviewScore: 93,
    totalReviews: 85000,
    isFree: false,
    genres: ['RPG', 'Macera', 'Bağımsız'],
    released: '2019-10-15',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_489830',
    rawgId: 489830,
    rawgSlug: 'the-elder-scrolls-v-skyrim-special-edition',
    name: 'The Elder Scrolls V: Skyrim Special Edition',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/489830/header.jpg',
    metacritic: 94,
    reviewScore: 94,
    totalReviews: 165000,
    isFree: false,
    genres: ['RPG', 'Macera'],
    released: '2016-10-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_413150',
    rawgId: 413150,
    rawgSlug: 'stardew-valley',
    name: 'Stardew Valley',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg',
    metacritic: 89,
    reviewScore: 98,
    totalReviews: 610000,
    isFree: false,
    genres: ['Simülasyon', 'RPG', 'Bağımsız'],
    released: '2016-02-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_814380',
    rawgId: 814380,
    rawgSlug: 'sekiro-shadows-die-twice',
    name: 'Sekiro: Shadows Die Twice',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg',
    metacritic: 88,
    reviewScore: 95,
    totalReviews: 210000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2019-03-22',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_582010',
    rawgId: 582010,
    rawgSlug: 'monster-hunter-world',
    name: 'Monster Hunter: World',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582010/header.jpg',
    metacritic: 88,
    reviewScore: 90,
    totalReviews: 260000,
    isFree: false,
    genres: ['Aksiyon', 'RPG'],
    released: '2018-08-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1426210',
    rawgId: 1426210,
    rawgSlug: 'it-takes-two',
    name: 'It Takes Two',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/header.jpg',
    metacritic: 89,
    reviewScore: 95,
    totalReviews: 145000,
    isFree: false,
    genres: ['Macera', 'Platform', 'Aksiyon'],
    released: '2021-03-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_105600',
    rawgId: 105600,
    rawgSlug: 'terraria',
    name: 'Terraria',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg',
    metacritic: 81,
    reviewScore: 97,
    totalReviews: 1100000,
    isFree: false,
    genres: ['Aksiyon', 'Macera', 'Platform', 'Bağımsız'],
    released: '2011-05-16',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_588650',
    rawgId: 588650,
    rawgSlug: 'dead-cells',
    name: 'Dead Cells',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg',
    metacritic: 89,
    reviewScore: 97,
    totalReviews: 140000,
    isFree: false,
    genres: ['Aksiyon', 'Platform', 'Bağımsız'],
    released: '2018-08-07',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_220',
    rawgId: 220,
    rawgSlug: 'half-life-2',
    name: 'Half-Life 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/220/header.jpg',
    metacritic: 96,
    reviewScore: 97,
    totalReviews: 180000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2004-11-16',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_8870',
    rawgId: 8870,
    rawgSlug: 'bioshock-infinite',
    name: 'BioShock Infinite',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/8870/header.jpg',
    metacritic: 94,
    reviewScore: 95,
    totalReviews: 160000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2013-03-25',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_7670',
    rawgId: 7670,
    rawgSlug: 'bioshock',
    name: 'BioShock',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/7670/header.jpg',
    metacritic: 96,
    reviewScore: 95,
    totalReviews: 48000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2007-08-21',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_24980',
    rawgId: 24980,
    rawgSlug: 'mass-effect-2',
    name: 'Mass Effect 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/24980/header.jpg',
    metacritic: 94,
    reviewScore: 95,
    totalReviews: 32000,
    isFree: false,
    genres: ['RPG', 'Nişancı', 'Aksiyon'],
    released: '2010-01-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_377160',
    rawgId: 377160,
    rawgSlug: 'fallout-4',
    name: 'Fallout 4',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/377160/header.jpg',
    metacritic: 84,
    reviewScore: 83,
    totalReviews: 240000,
    isFree: false,
    genres: ['RPG', 'Nişancı', 'Aksiyon'],
    released: '2015-11-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_22380',
    rawgId: 22380,
    rawgSlug: 'fallout-new-vegas',
    name: 'Fallout: New Vegas',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/22380/header.jpg',
    metacritic: 84,
    reviewScore: 96,
    totalReviews: 185000,
    isFree: false,
    genres: ['RPG', 'Aksiyon'],
    released: '2010-10-19',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_435150',
    rawgId: 435150,
    rawgSlug: 'divinity-original-sin-2',
    name: 'Divinity: Original Sin 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/435150/header.jpg',
    metacritic: 93,
    reviewScore: 95,
    totalReviews: 155000,
    isFree: false,
    genres: ['RPG', 'Strateji'],
    released: '2017-09-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_782330',
    rawgId: 782330,
    rawgSlug: 'doom-eternal',
    name: 'Doom Eternal',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg',
    metacritic: 88,
    reviewScore: 91,
    totalReviews: 175000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2020-03-19',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2050650',
    rawgId: 2050650,
    rawgSlug: 'resident-evil-4',
    name: 'Resident Evil 4',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg',
    metacritic: 93,
    reviewScore: 97,
    totalReviews: 85000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2023-03-24',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_883710',
    rawgId: 883710,
    rawgSlug: 'resident-evil-2',
    name: 'Resident Evil 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/883710/header.jpg',
    metacritic: 89,
    reviewScore: 97,
    totalReviews: 110000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2019-01-25',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_203160',
    rawgId: 203160,
    rawgSlug: 'tomb-raider',
    name: 'Tomb Raider',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/203160/header.jpg',
    metacritic: 86,
    reviewScore: 96,
    totalReviews: 150000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2013-03-05',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_391220',
    rawgId: 391220,
    rawgSlug: 'rise-of-the-tomb-raider',
    name: 'Rise of the Tomb Raider',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/391220/header.jpg',
    metacritic: 86,
    reviewScore: 94,
    totalReviews: 98000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2016-02-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_750920',
    rawgId: 750920,
    rawgSlug: 'shadow-of-the-tomb-raider',
    name: 'Shadow of the Tomb Raider',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/750920/header.jpg',
    metacritic: 82,
    reviewScore: 85,
    totalReviews: 68000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2018-09-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_812140',
    rawgId: 812140,
    rawgSlug: 'assassins-creed-odyssey',
    name: "Assassin's Creed Odyssey",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/812140/header.jpg',
    metacritic: 83,
    reviewScore: 89,
    totalReviews: 140000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Macera'],
    released: '2018-10-05',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_582160',
    rawgId: 582160,
    rawgSlug: 'assassins-creed-origins',
    name: "Assassin's Creed Origins",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582160/header.jpg',
    metacritic: 84,
    reviewScore: 86,
    totalReviews: 92000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Macera'],
    released: '2017-10-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2208920',
    rawgId: 2208920,
    rawgSlug: 'assassins-creed-valhalla',
    name: "Assassin's Creed Valhalla",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2208920/header.jpg',
    metacritic: 80,
    reviewScore: 75,
    totalReviews: 22000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Macera'],
    released: '2020-11-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_870780',
    rawgId: 870780,
    rawgSlug: 'control-ultimate-edition',
    name: 'Control Ultimate Edition',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/header.jpg',
    metacritic: 82,
    reviewScore: 88,
    totalReviews: 35000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2019-08-27',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_1252330',
    rawgId: 1252330,
    rawgSlug: 'deathloop',
    name: 'DEATHLOOP',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1252330/header.jpg',
    metacritic: 88,
    reviewScore: 77,
    totalReviews: 18000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2021-09-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_205100',
    rawgId: 205100,
    rawgSlug: 'dishonored',
    name: 'Dishonored',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/205100/header.jpg',
    metacritic: 91,
    reviewScore: 97,
    totalReviews: 65000,
    isFree: false,
    genres: ['Aksiyon', 'Gizlilik', 'Macera'],
    released: '2012-10-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_403640',
    rawgId: 403640,
    rawgSlug: 'dishonored-2',
    name: 'Dishonored 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/403640/header.jpg',
    metacritic: 86,
    reviewScore: 89,
    totalReviews: 38000,
    isFree: false,
    genres: ['Aksiyon', 'Gizlilik', 'Macera'],
    released: '2016-11-11',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_480490',
    rawgId: 480490,
    rawgSlug: 'prey',
    name: 'Prey',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/480490/header.jpg',
    metacritic: 82,
    reviewScore: 90,
    totalReviews: 34000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı', 'Macera'],
    released: '2017-05-05',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_412020',
    rawgId: 412020,
    rawgSlug: 'metro-exodus',
    name: 'Metro Exodus',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/412020/header.jpg',
    metacritic: 82,
    reviewScore: 89,
    totalReviews: 92000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı', 'Korku'],
    released: '2019-02-15',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_264710',
    rawgId: 264710,
    rawgSlug: 'subnautica',
    name: 'Subnautica',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg',
    metacritic: 87,
    reviewScore: 96,
    totalReviews: 230000,
    isFree: false,
    genres: ['Macera', 'Simülasyon', 'Bağımsız'],
    released: '2018-01-23',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_753640',
    rawgId: 753640,
    rawgSlug: 'outer-wilds',
    name: 'Outer Wilds',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/753640/header.jpg',
    metacritic: 85,
    reviewScore: 95,
    totalReviews: 54000,
    isFree: false,
    genres: ['Macera', 'Bulmaca', 'Bağımsız'],
    released: '2019-05-28',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1332010',
    rawgId: 1332010,
    rawgSlug: 'stray',
    name: 'Stray',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/header.jpg',
    metacritic: 83,
    reviewScore: 97,
    totalReviews: 125000,
    isFree: false,
    genres: ['Macera', 'Bağımsız'],
    released: '2022-07-19',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_990080',
    rawgId: 990080,
    rawgSlug: 'hogwarts-legacy',
    name: 'Hogwarts Legacy',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg',
    metacritic: 84,
    reviewScore: 91,
    totalReviews: 185000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Macera'],
    released: '2023-02-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1774580',
    rawgId: 1774580,
    rawgSlug: 'star-wars-jedi-survivor',
    name: 'STAR WARS Jedi: Survivor',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1774580/header.jpg',
    metacritic: 85,
    reviewScore: 67,
    totalReviews: 45000,
    isFree: false,
    genres: ['Aksiyon', 'Macera'],
    released: '2023-04-28',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1145350',
    rawgId: 1145350,
    rawgSlug: 'hades-ii',
    name: 'Hades II',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg',
    metacritic: 90,
    reviewScore: 95,
    totalReviews: 42000,
    isFree: false,
    genres: ['Aksiyon', 'RPG', 'Bağımsız'],
    released: '2024-05-06',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Korku (Horror)
  {
    id: 'rawg_1693980',
    rawgId: 1693980,
    rawgSlug: 'dead-space',
    name: 'Dead Space',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/header.jpg',
    metacritic: 89,
    reviewScore: 91,
    totalReviews: 32000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2023-01-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_739630',
    rawgId: 739630,
    rawgSlug: 'phasmophobia',
    name: 'Phasmophobia',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/739630/header.jpg',
    metacritic: 85,
    reviewScore: 96,
    totalReviews: 550000,
    isFree: false,
    genres: ['Korku', 'Bağımsız', 'Aksiyon'],
    released: '2020-09-18',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_238320',
    rawgId: 238320,
    rawgSlug: 'outlast',
    name: 'Outlast',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/238320/header.jpg',
    metacritic: 80,
    reviewScore: 96,
    totalReviews: 82000,
    isFree: false,
    genres: ['Korku', 'Macera', 'Bağımsız'],
    released: '2013-09-04',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_414700',
    rawgId: 414700,
    rawgSlug: 'outlast-2',
    name: 'Outlast 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/414700/header.jpg',
    metacritic: 75,
    reviewScore: 89,
    totalReviews: 45000,
    isFree: false,
    genres: ['Korku', 'Macera', 'Bağımsız'],
    released: '2017-04-25',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_242760',
    rawgId: 242760,
    rawgSlug: 'the-forest',
    name: 'The Forest',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/242760/header.jpg',
    metacritic: 83,
    reviewScore: 95,
    totalReviews: 450000,
    isFree: false,
    genres: ['Korku', 'Simülasyon', 'Aksiyon'],
    released: '2018-04-30',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1326470',
    rawgId: 1326470,
    rawgSlug: 'sons-of-the-forest',
    name: 'Sons of the Forest',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1326470/header.jpg',
    metacritic: 86,
    reviewScore: 86,
    totalReviews: 175000,
    isFree: false,
    genres: ['Korku', 'Simülasyon', 'Aksiyon'],
    released: '2024-02-22',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_57300',
    rawgId: 57300,
    rawgSlug: 'amnesia-the-dark-descent',
    name: 'Amnesia: The Dark Descent',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/57300/header.jpg',
    metacritic: 85,
    reviewScore: 95,
    totalReviews: 32000,
    isFree: false,
    genres: ['Korku', 'Macera', 'Bağımsız'],
    released: '2010-09-08',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1944430',
    rawgId: 1944430,
    rawgSlug: 'amnesia-the-bunker',
    name: 'Amnesia: The Bunker',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1944430/header.jpg',
    metacritic: 78,
    reviewScore: 92,
    totalReviews: 12000,
    isFree: false,
    genres: ['Korku', 'Aksiyon', 'Macera'],
    released: '2023-06-06',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_418370',
    rawgId: 418370,
    rawgSlug: 'resident-evil-7-biohazard',
    name: 'Resident Evil 7 Biohazard',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/418370/header.jpg',
    metacritic: 86,
    reviewScore: 95,
    totalReviews: 54000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2017-01-24',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1196590',
    rawgId: 1196590,
    rawgSlug: 'resident-evil-village',
    name: 'Resident Evil Village',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1196590/header.jpg',
    metacritic: 84,
    reviewScore: 95,
    totalReviews: 72000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2021-05-07',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_268050',
    rawgId: 268050,
    rawgSlug: 'the-evil-within',
    name: 'The Evil Within',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268050/header.jpg',
    metacritic: 75,
    reviewScore: 84,
    totalReviews: 21000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2014-10-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_601430',
    rawgId: 601430,
    rawgSlug: 'the-evil-within-2',
    name: 'The Evil Within 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/601430/header.jpg',
    metacritic: 80,
    reviewScore: 92,
    totalReviews: 18000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2017-10-13',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_214490',
    rawgId: 214490,
    rawgSlug: 'alien-isolation',
    name: 'Alien: Isolation',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/214490/header.jpg',
    metacritic: 81,
    reviewScore: 92,
    totalReviews: 42000,
    isFree: false,
    genres: ['Aksiyon', 'Korku'],
    released: '2014-10-06',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_381210',
    rawgId: 381210,
    rawgSlug: 'dead-by-daylight',
    name: 'Dead by Daylight',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/381210/header.jpg',
    metacritic: 71,
    reviewScore: 80,
    totalReviews: 540000,
    isFree: false,
    genres: ['Korku', 'Aksiyon'],
    released: '2016-06-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_239140',
    rawgId: 239140,
    rawgSlug: 'dying-light',
    name: 'Dying Light',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/239140/header.jpg',
    metacritic: 75,
    reviewScore: 95,
    totalReviews: 290000,
    isFree: false,
    genres: ['Aksiyon', 'Korku', 'RPG'],
    released: '2015-01-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Strateji (Strategy)
  {
    id: 'rawg_289070',
    rawgId: 289070,
    rawgSlug: 'sid-meiers-civilization-vi',
    name: "Sid Meier's Civilization VI",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg',
    metacritic: 88,
    reviewScore: 86,
    totalReviews: 220000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon'],
    released: '2016-10-21',
    hasSteam: true,
    hasEpic: true,
    hasStores: true
  },
  {
    id: 'rawg_268500',
    rawgId: 268500,
    rawgSlug: 'xcom-2',
    name: 'XCOM 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268500/header.jpg',
    metacritic: 88,
    reviewScore: 87,
    totalReviews: 72000,
    isFree: false,
    genres: ['Strateji', 'Aksiyon'],
    released: '2016-02-05',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1158310',
    rawgId: 1158310,
    rawgSlug: 'crusader-kings-iii',
    name: 'Crusader Kings III',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1158310/header.jpg',
    metacritic: 91,
    reviewScore: 91,
    totalReviews: 68000,
    isFree: false,
    genres: ['Strateji', 'RPG', 'Simülasyon'],
    released: '2020-09-01',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_427520',
    rawgId: 427520,
    rawgSlug: 'factorio',
    name: 'Factorio',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/427520/header.jpg',
    metacritic: 90,
    reviewScore: 98,
    totalReviews: 140000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon', 'Bağımsız'],
    released: '2020-08-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1142710',
    rawgId: 1142710,
    rawgSlug: 'total-war-warhammer-iii',
    name: 'Total War: WARHAMMER III',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1142710/header.jpg',
    metacritic: 85,
    reviewScore: 76,
    totalReviews: 62000,
    isFree: false,
    genres: ['Strateji', 'Aksiyon'],
    released: '2022-02-17',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_813780',
    rawgId: 813780,
    rawgSlug: 'age-of-empires-ii-definitive-edition',
    name: 'Age of Empires II: Definitive Edition',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/813780/header.jpg',
    metacritic: 84,
    reviewScore: 94,
    totalReviews: 125000,
    isFree: false,
    genres: ['Strateji'],
    released: '2019-11-14',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1466860',
    rawgId: 1466860,
    rawgSlug: 'age-of-empires-iv-anniversary-edition',
    name: 'Age of Empires IV: Anniversary Edition',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1466860/header.jpg',
    metacritic: 81,
    reviewScore: 86,
    totalReviews: 45000,
    isFree: false,
    genres: ['Strateji'],
    released: '2021-10-28',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_281990',
    rawgId: 281990,
    rawgSlug: 'stellaris',
    name: 'Stellaris',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/281990/header.jpg',
    metacritic: 78,
    reviewScore: 88,
    totalReviews: 110000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon'],
    released: '2016-05-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_394360',
    rawgId: 394360,
    rawgSlug: 'hearts-of-iron-iv',
    name: 'Hearts of Iron IV',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/394360/header.jpg',
    metacritic: 81,
    reviewScore: 92,
    totalReviews: 195000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon'],
    released: '2016-06-06',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_294100',
    rawgId: 294100,
    rawgSlug: 'rimworld',
    name: 'RimWorld',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/294100/header.jpg',
    metacritic: 87,
    reviewScore: 98,
    totalReviews: 155000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon', 'Bağımsız'],
    released: '2018-10-17',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_323190',
    rawgId: 323190,
    rawgSlug: 'frostpunk',
    name: 'Frostpunk',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/323190/header.jpg',
    metacritic: 84,
    reviewScore: 92,
    totalReviews: 85000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon', 'Bağımsız'],
    released: '2018-04-24',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2379780',
    rawgId: 2379780,
    rawgSlug: 'balatro',
    name: 'Balatro',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2379780/header.jpg',
    metacritic: 90,
    reviewScore: 96,
    totalReviews: 38000,
    isFree: false,
    genres: ['Strateji', 'Kart & Masa', 'Bağımsız'],
    released: '2024-02-20',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1363080',
    rawgId: 1363080,
    rawgSlug: 'manor-lords',
    name: 'Manor Lords',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1363080/header.jpg',
    metacritic: 88,
    reviewScore: 88,
    totalReviews: 45000,
    isFree: false,
    genres: ['Strateji', 'Simülasyon'],
    released: '2024-04-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Simülasyon (Simulation)
  {
    id: 'rawg_255710',
    rawgId: 255710,
    rawgSlug: 'cities-skylines',
    name: 'Cities: Skylines',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/255710/header.jpg',
    metacritic: 85,
    reviewScore: 93,
    totalReviews: 185000,
    isFree: false,
    genres: ['Simülasyon', 'Strateji'],
    released: '2015-03-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1250410',
    rawgId: 1250410,
    rawgSlug: 'microsoft-flight-simulator-40th-anniversary-edition',
    name: 'Microsoft Flight Simulator 40th Anniversary Edition',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1250410/header.jpg',
    metacritic: 91,
    reviewScore: 90,
    totalReviews: 54000,
    isFree: false,
    genres: ['Simülasyon'],
    released: '2020-08-18',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_227300',
    rawgId: 227300,
    rawgSlug: 'euro-truck-simulator-2',
    name: 'Euro Truck Simulator 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg',
    metacritic: 79,
    reviewScore: 97,
    totalReviews: 580000,
    isFree: false,
    genres: ['Simülasyon', 'Yarış'],
    released: '2012-10-18',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_270880',
    rawgId: 270880,
    rawgSlug: 'american-truck-simulator',
    name: 'American Truck Simulator',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/270880/header.jpg',
    metacritic: 76,
    reviewScore: 96,
    totalReviews: 75000,
    isFree: false,
    genres: ['Simülasyon'],
    released: '2016-02-02',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_613100',
    rawgId: 613100,
    rawgSlug: 'house-flipper',
    name: 'House Flipper',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/header.jpg',
    metacritic: 68,
    reviewScore: 93,
    totalReviews: 78000,
    isFree: false,
    genres: ['Simülasyon', 'Bağımsız'],
    released: '2018-05-17',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_220200',
    rawgId: 220200,
    rawgSlug: 'kerbal-space-program',
    name: 'Kerbal Space Program',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/220200/header.jpg',
    metacritic: 88,
    reviewScore: 95,
    totalReviews: 92000,
    isFree: false,
    genres: ['Simülasyon', 'Strateji'],
    released: '2015-04-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1248130',
    rawgId: 1248130,
    rawgSlug: 'farming-simulator-22',
    name: 'Farming Simulator 22',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1248130/header.jpg',
    metacritic: 75,
    reviewScore: 92,
    totalReviews: 45000,
    isFree: false,
    genres: ['Simülasyon'],
    released: '2021-11-22',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2670630',
    rawgId: 2670630,
    rawgSlug: 'supermarket-simulator',
    name: 'Supermarket Simulator',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2670630/header.jpg',
    metacritic: 82,
    reviewScore: 94,
    totalReviews: 32000,
    isFree: false,
    genres: ['Simülasyon', 'Bağımsız'],
    released: '2024-02-20',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Spor & Yarış (Sports & Racing)
  {
    id: 'rawg_1551360',
    rawgId: 1551360,
    rawgSlug: 'forza-horizon-5',
    name: 'Forza Horizon 5',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
    metacritic: 92,
    reviewScore: 88,
    totalReviews: 165000,
    isFree: false,
    genres: ['Yarış', 'Spor', 'Aksiyon'],
    released: '2021-11-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1293830',
    rawgId: 1293830,
    rawgSlug: 'forza-horizon-4',
    name: 'Forza Horizon 4',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1293830/header.jpg',
    metacritic: 92,
    reviewScore: 89,
    totalReviews: 210000,
    isFree: false,
    genres: ['Yarış', 'Spor'],
    released: '2021-03-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1222680',
    rawgId: 1222680,
    rawgSlug: 'need-for-speed-heat',
    name: 'Need for Speed Heat',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222680/header.jpg',
    metacritic: 72,
    reviewScore: 83,
    totalReviews: 88000,
    isFree: false,
    genres: ['Yarış', 'Aksiyon'],
    released: '2019-11-08',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_690790',
    rawgId: 690790,
    rawgSlug: 'dirt-rally-20',
    name: 'DiRT Rally 2.0',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/690790/header.jpg',
    metacritic: 84,
    reviewScore: 87,
    totalReviews: 32000,
    isFree: false,
    genres: ['Yarış', 'Simülasyon', 'Spor'],
    released: '2019-02-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_244210',
    rawgId: 244210,
    rawgSlug: 'assetto-corsa',
    name: 'Assetto Corsa',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/244210/header.jpg',
    metacritic: 85,
    reviewScore: 92,
    totalReviews: 95000,
    isFree: false,
    genres: ['Yarış', 'Simülasyon', 'Spor'],
    released: '2014-12-19',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2108330',
    rawgId: 2108330,
    rawgSlug: 'f1-23',
    name: 'F1 23',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2108330/header.jpg',
    metacritic: 84,
    reviewScore: 85,
    totalReviews: 14000,
    isFree: false,
    genres: ['Yarış', 'Simülasyon', 'Spor'],
    released: '2023-06-16',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2195250',
    rawgId: 2195250,
    rawgSlug: 'ea-sports-fc-24',
    name: 'EA SPORTS FC 24',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2195250/header.jpg',
    metacritic: 75,
    reviewScore: 55,
    totalReviews: 54000,
    isFree: false,
    genres: ['Spor', 'Simülasyon'],
    released: '2023-09-29',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1904720',
    rawgId: 1904720,
    rawgSlug: 'tony-hawks-pro-skater-1-2',
    name: "Tony Hawk's Pro Skater 1 + 2",
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1904720/header.jpg',
    metacritic: 88,
    reviewScore: 90,
    totalReviews: 8200,
    isFree: false,
    genres: ['Spor'],
    released: '2023-10-03',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Bulmaca (Puzzle)
  {
    id: 'rawg_210970',
    rawgId: 210970,
    rawgSlug: 'the-witness',
    name: 'The Witness',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/210970/header.jpg',
    metacritic: 87,
    reviewScore: 85,
    totalReviews: 12000,
    isFree: false,
    genres: ['Bulmaca', 'Bağımsız'],
    released: '2016-01-26',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_257510',
    rawgId: 257510,
    rawgSlug: 'the-talos-principle',
    name: 'The Talos Principle',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/257510/header.jpg',
    metacritic: 85,
    reviewScore: 95,
    totalReviews: 32000,
    isFree: false,
    genres: ['Bulmaca', 'Bağımsız'],
    released: '2014-12-11',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_830130',
    rawgId: 830130,
    rawgSlug: 'the-talos-principle-2',
    name: 'The Talos Principle 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/830130/header.jpg',
    metacritic: 88,
    reviewScore: 95,
    totalReviews: 8500,
    isFree: false,
    genres: ['Bulmaca'],
    released: '2023-11-02',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_736260',
    rawgId: 736260,
    rawgSlug: 'baba-is-you',
    name: 'Baba Is You',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/736260/header.jpg',
    metacritic: 87,
    reviewScore: 98,
    totalReviews: 18000,
    isFree: false,
    genres: ['Bulmaca', 'Bağımsız'],
    released: '2019-03-13',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_48000',
    rawgId: 48000,
    rawgSlug: 'limbo',
    name: 'LIMBO',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/48000/header.jpg',
    metacritic: 88,
    reviewScore: 93,
    totalReviews: 54000,
    isFree: false,
    genres: ['Platform', 'Bulmaca', 'Bağımsız', 'Macera'],
    released: '2011-08-02',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_304430',
    rawgId: 304430,
    rawgSlug: 'inside',
    name: 'INSIDE',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/304430/header.jpg',
    metacritic: 93,
    reviewScore: 95,
    totalReviews: 48000,
    isFree: false,
    genres: ['Platform', 'Bulmaca', 'Bağımsız', 'Macera'],
    released: '2016-07-07',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1222730',
    rawgId: 1222730,
    rawgSlug: 'unravel',
    name: 'Unravel',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222730/header.jpg',
    metacritic: 81,
    reviewScore: 92,
    totalReviews: 32000,
    isFree: false,
    genres: ['Platform', 'Bulmaca', 'Macera'],
    released: '2016-02-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Nişancı (Shooter)
  {
    id: 'rawg_379720',
    rawgId: 379720,
    rawgSlug: 'doom',
    name: 'DOOM',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/379720/header.jpg',
    metacritic: 85,
    reviewScore: 95,
    totalReviews: 185000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2016-05-13',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1237970',
    rawgId: 1237970,
    rawgSlug: 'titanfall-2',
    name: 'Titanfall 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1237970/header.jpg',
    metacritic: 89,
    reviewScore: 94,
    totalReviews: 180000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2016-10-28',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_49520',
    rawgId: 49520,
    rawgSlug: 'borderlands-2',
    name: 'Borderlands 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/49520/header.jpg',
    metacritic: 89,
    reviewScore: 94,
    totalReviews: 210000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı', 'RPG'],
    released: '2012-09-18',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_976730',
    rawgId: 976730,
    rawgSlug: 'halo-the-master-chief-collection',
    name: 'Halo: The Master Chief Collection',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/976730/header.jpg',
    metacritic: 93,
    reviewScore: 93,
    totalReviews: 110000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2019-12-03',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_553850',
    rawgId: 553850,
    rawgSlug: 'helldivers-2',
    name: 'Helldivers 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg',
    metacritic: 82,
    reviewScore: 88,
    totalReviews: 195000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2024-02-08',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_201810',
    rawgId: 201810,
    rawgSlug: 'wolfenstein-the-new-order',
    name: 'Wolfenstein: The New Order',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/201810/header.jpg',
    metacritic: 81,
    reviewScore: 90,
    totalReviews: 45000,
    isFree: false,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2014-05-20',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Kart & Masa (Card & Board)
  {
    id: 'rawg_646570',
    rawgId: 646570,
    rawgSlug: 'slay-the-spire',
    name: 'Slay the Spire',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg',
    metacritic: 89,
    reviewScore: 97,
    totalReviews: 125000,
    isFree: false,
    genres: ['Strateji', 'Kart & Masa', 'Bağımsız'],
    released: '2019-01-23',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_286160',
    rawgId: 286160,
    rawgSlug: 'tabletop-simulator',
    name: 'Tabletop Simulator',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/286160/header.jpg',
    metacritic: 85,
    reviewScore: 96,
    totalReviews: 42000,
    isFree: false,
    genres: ['Kart & Masa', 'Simülasyon'],
    released: '2015-06-05',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1092790',
    rawgId: 1092790,
    rawgSlug: 'inscryption',
    name: 'Inscryption',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1092790/header.jpg',
    metacritic: 87,
    reviewScore: 97,
    totalReviews: 95000,
    isFree: false,
    genres: ['Kart & Masa', 'Bulmaca', 'Bağımsız'],
    released: '2021-10-19',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },

  // Ücretsiz (Free to Play)
  {
    id: 'rawg_730',
    rawgId: 730,
    rawgSlug: 'counter-strike-2',
    name: 'Counter-Strike 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg',
    metacritic: 88,
    reviewScore: 88,
    totalReviews: 8100000,
    isFree: true,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2023-09-27',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_570',
    rawgId: 570,
    rawgSlug: 'dota-2',
    name: 'Dota 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg',
    metacritic: 90,
    reviewScore: 82,
    totalReviews: 2200000,
    isFree: true,
    genres: ['Strateji'],
    released: '2013-07-09',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1172470',
    rawgId: 1172470,
    rawgSlug: 'apex-legends',
    name: 'Apex Legends',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg',
    metacritic: 88,
    reviewScore: 80,
    totalReviews: 820000,
    isFree: true,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2020-11-04',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_578080',
    rawgId: 578080,
    rawgSlug: 'pubg-battlegrounds',
    name: 'PUBG: BATTLEGROUNDS',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg',
    metacritic: 86,
    reviewScore: 57,
    totalReviews: 2400000,
    isFree: true,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2017-12-21',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_230410',
    rawgId: 230410,
    rawgSlug: 'warframe',
    name: 'Warframe',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/230410/header.jpg',
    metacritic: 69,
    reviewScore: 87,
    totalReviews: 560000,
    isFree: true,
    genres: ['Aksiyon', 'RPG'],
    released: '2013-03-25',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_440',
    rawgId: 440,
    rawgSlug: 'team-fortress-2',
    name: 'Team Fortress 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/440/header.jpg',
    metacritic: 92,
    reviewScore: 93,
    totalReviews: 960000,
    isFree: true,
    genres: ['Aksiyon', 'Nişancı'],
    released: '2007-10-10',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_1085660',
    rawgId: 1085660,
    rawgSlug: 'destiny-2',
    name: 'Destiny 2',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg',
    metacritic: 83,
    reviewScore: 82,
    totalReviews: 590000,
    isFree: true,
    genres: ['Aksiyon', 'Nişancı', 'RPG'],
    released: '2019-10-01',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_238960',
    rawgId: 238960,
    rawgSlug: 'path-of-exile',
    name: 'Path of Exile',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/238960/header.jpg',
    metacritic: 86,
    reviewScore: 91,
    totalReviews: 220000,
    isFree: true,
    genres: ['RPG', 'Aksiyon', 'Bağımsız'],
    released: '2013-10-23',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_291550',
    rawgId: 291550,
    rawgSlug: 'brawlhalla',
    name: 'Brawlhalla',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/291550/header.jpg',
    metacritic: 70,
    reviewScore: 86,
    totalReviews: 380000,
    isFree: true,
    genres: ['Aksiyon', 'Platform'],
    released: '2017-10-17',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_236390',
    rawgId: 236390,
    rawgSlug: 'war-thunder',
    name: 'War Thunder',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/236390/header.jpg',
    metacritic: 81,
    reviewScore: 85,
    totalReviews: 480000,
    isFree: true,
    genres: ['Simülasyon', 'Aksiyon'],
    released: '2013-08-15',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_3513350',
    rawgId: 3513350,
    rawgSlug: 'wuthering-waves',
    name: 'Wuthering Waves',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3513350/header.jpg',
    metacritic: 83,
    reviewScore: 80,
    totalReviews: 15000,
    isFree: true,
    genres: ['RPG', 'Aksiyon', 'Macera'],
    released: '2024-05-22',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  },
  {
    id: 'rawg_2429640',
    rawgId: 2429640,
    rawgSlug: 'throne-and-liberty',
    name: 'Throne and Liberty',
    image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2429640/header.jpg',
    metacritic: 75,
    reviewScore: 70,
    totalReviews: 24000,
    isFree: true,
    genres: ['RPG', 'Aksiyon'],
    released: '2024-10-01',
    hasSteam: true,
    hasEpic: false,
    hasStores: true
  }
];
