import { createContext, useContext, useState, useCallback, useMemo } from 'react';

// Web sitesindeki dil sistemiyle uyumlu, mobil için sadeleştirilmiş sürüm.
const STRINGS = {
  tr: {
    'nav.home': 'Anasayfa',
    'home.reviewPrompt': 'Bunları oynadın — ne düşünüyorsun?',
    'home.friendsPlaying': 'Arkadaşların bu hafta',
    'nav.games': 'Oyunlar',
    'nav.news': 'Haberler',
    'nav.videos': 'Videolar',
    'nav.library': 'Kütüphane',
    'nav.profile': 'Profil',
    'nav.messages': 'Mesajlar',
    'news.title': 'Haberler',
    'news.all': 'Tümü',
    'news.empty': 'Haber bulunamadı',
    'news.featured': 'ÖNE ÇIKAN',
    'games.title': 'Oyunlar',
    'games.searchPlaceholder': 'Oyun ara…',
    'games.noResults': 'Sonuç bulunamadı',
    'games.loading': 'Yükleniyor…',
    'card.free': 'Ücretsiz',
    'section.all': 'Tümü',
    'section.popular': 'Popüler',
    'section.new': 'Yeni Çıkan',
    'section.sale': 'İndirimde',
    'section.free': 'Ücretsiz',
    'section.topscore': 'En İyi Puan',
    'mode.all': 'Tüm Modlar',
    'mode.singleplayer': 'Tek Oyunculu',
    'mode.multiplayer': 'Çok Oyunculu',
    'mode.coop': 'Co-op',
    'home.tagline': 'PC oyunlarını keşfet, fiyatları karşılaştır, kütüphaneni bağla.',
    'home.exploreGames': 'Oyunları Keşfet',
    'hero.badge': 'Canlı fiyat karşılaştırma',
    'hero.subtitle': 'Zevkine göre öneriler — Steam, Epic, GOG ve Humble fiyatlarını tek ekranda karşılaştır',
    'hero.search': 'Oyun ara…',
    'home.forYou': 'Senin İçin',
    'home.trend': 'Bu Hafta Trend',
    'home.new': 'Yeni Çıkanlar',
    'home.sale': 'İndirimdekiler',
    'home.viewAll': 'Tümü',
    'acc.or': 'veya',
    'acc.appleReauth': 'Silme işlemini onaylamak için Apple ile tekrar doğrula',
    'acc.appleReauthBtn': 'Apple ile doğrula ve sil',
    'acc.signIn': 'Giriş yap',
    'acc.signUp': 'Hesap oluştur',
    'acc.name': 'Adın',
    'acc.email': 'E-posta',
    'acc.password': 'Şifre',
    'acc.haveAccount': 'Zaten hesabın var mı? Giriş yap',
    'acc.noAccount': 'Hesabın yok mu? Oluştur',
    'acc.forgot': 'Şifremi unuttum',
    'acc.signOut': 'Çıkış yap',
    'acc.signedInAs': 'Giriş yapıldı',
    'acc.why': 'Hesabınla zevk profilin ve takip listen tüm cihazlarında aynı kalır.',
    // Misafirken biriken veri hesaba SESSİZCE aktarılmaz — ortak cihazda bu,
    // başkasının verisini senin hesabına yazmak demek olurdu.
    'acc.transferTitle': 'Cihazdaki veriler',
    'acc.transferBody': 'Hesapsız kullanırken oluşturulmuş {n} bu hesaba aktarılsın mı?',
    'acc.transferCollections': '{n} koleksiyon',
    'acc.transferWishlist': '{n} takip',
    'acc.transferYes': 'Aktar',
    'acc.transferNo': 'Aktarma',
    'acc.verifySent': 'Doğrulama e-postası gönderildi. Adresini onayladıktan sonra giriş yapabilirsin.',
    'acc.resetSent': 'Şifre sıfırlama bağlantısı e-postana gönderildi.',
    'acc.notVerified': 'E-posta adresin henüz doğrulanmamış. Gelen kutunu kontrol et.',
    'acc.deleteTitle': 'Hesabı sil',
    'acc.deleteWarn': 'Hesabın ve sunucudaki verilerin kalıcı olarak silinir. Bu işlem geri alınamaz.',
    'acc.deleteConfirm': 'Hesabımı kalıcı olarak sil',
    'acc.emailRequired': 'Lütfen e-posta adresinizi girin.',
    'acc.passwordRequired': 'Lütfen şifrenizi girin.',
    'acc.passwordTooShort': 'Şifre en az 6 karakter olmalıdır.',
    'acc.nameRequired': 'Lütfen adınızı girin.',
    'acc.sendResetLink': 'Sıfırlama Bağlantısı Gönder',
    'acc.backToSignIn': 'Giriş Yap Ekranına Dön',
    'onb.title': 'Hangilerini sevdin?',
    'onb.subtitle': 'Birkaç oyun seç, sana özel önerileri hemen hazırlayalım.',
    'onb.selected': 'seçildi',
    'onb.need': 'En az 3 oyun seç',
    'onb.continue': 'Devam et',
    'onb.skip': 'Şimdilik geç',
    'onb.retake': 'Zevkini yeniden seç',
    'onb.done': 'Zevkin güncellendi',
    'swipe.title': 'Keşfet',
    'swipe.subtitle': 'Sağa kaydır: ilgimi çekti · Sola: bana göre değil',
    'swipe.like': 'İLGİMİ ÇEKTİ',
    'swipe.pass': 'BANA GÖRE DEĞİL',
    'swipe.liked': 'beğeni',
    'swipe.passed': 'geçildi',
    'swipe.emptyTitle': 'Şimdilik bu kadar',
    'swipe.emptyText': 'Yeni oyunlar geldikçe burada görünecek. Beğendiklerin önerilerini şekillendirmeye başladı bile.',
    'swipe.entry': 'Kaydırarak keşfet',
    'col.title': 'Koleksiyonlarım',
    'col.entry': 'Koleksiyonlarım',
    'col.empty': 'Henüz koleksiyonun yok',
    'col.emptyText': 'Oyunları kendi listelerinde topla: bitirdiklerin, favorilerin, co-op oynadıkların…',
    'col.new': 'Yeni koleksiyon',
    'col.create': 'Oluştur',
    'col.cancel': 'Vazgeç',
    'col.namePlaceholder': 'Koleksiyon adı',
    'col.rename': 'Yeniden adlandır',
    'col.save': 'Kaydet',
    'col.delete': 'Koleksiyonu sil',
    'col.deleteConfirm': 'Bu koleksiyon silinsin mi? Oyunlar silinmez, yalnızca liste kaldırılır.',
    'col.gameCount': 'oyun',
    'col.emptyList': 'Bu koleksiyon boş',
    'col.emptyListText': 'Oyun detay sayfasından koleksiyona ekleyebilirsin.',
    'col.addTo': 'Koleksiyona ekle',
    'col.added': 'Eklendi',
    'col.removeGame': 'Listeden çıkar',
    'col.limitReached': 'En fazla 50 koleksiyon oluşturabilirsin',
    'col.suggest1': 'Bitirdiğim Oyunlar',
    'col.suggest2': '2026 Favorilerim',
    'col.suggest3': 'Co-op Oyunlarım',
    'vid.title': 'Oyun Videoları',
    'vid.entry': 'Oyun videoları',
    'vid.loading': 'Videolar hazırlanıyor…',
    'vid.follow': 'Takip',
    'vid.save': 'Kaydet',
    'vid.buy': 'Satın al',
    'vid.mute': 'Sesi kapat',
    'vid.unmute': 'Sesi aç',
    'vid.detail': 'Oyun detayına git',
    'stats.title': 'Bu Haftan',
    'stats.entry': 'Haftalık raporun',
    'stats.subtitle': 'Son 7 günde neler yaptın',
    'stats.discovered': 'oyun keşfettin',
    'stats.liked': 'oyunu beğendin',
    'stats.passed': 'oyunu geçtin',
    'stats.wishlist': 'oyun takip ediyorsun',
    'stats.collections': 'koleksiyonun var',
    'stats.collected': 'oyun listelerinde',
    'stats.topGenre': 'En çok incelediğin tür',
    'stats.avgDiscount': 'Takip listendeki ortalama indirim',
    'stats.bestDiscount': 'En yüksek indirim',
    'stats.onSale': 'oyun indirimde',
    'stats.genreTitle': 'Tür dağılımın',
    'stats.emptyTitle': 'Henüz veri yok',
    'stats.emptyText': 'Biraz oyun keşfet, kaydır ve listeler oluştur — haftalık raporun burada oluşacak.',
    'stats.startBrowsing': 'Oyunlara göz at',
    'stats.startSwiping': 'Kaydırarak başla',
    'stats.share': 'Paylaş',
    'stats.decisions': 'karar verdin',
    // ── Sosyal ──
    'soc.entry': 'Arkadaşlar',
    // ── Steam arkadaslari ──
    'sf.title': 'Steam Arkadaşların',
    // ── Oyun kartlari ──
    'gc.title': 'Oyun Kartların',
    'gc.addCity': 'Şehrimi karta ekle',
    'gc.locOff': 'Kapalı — konum paylaşılmıyor',
    'gc.locResolving': 'Şehir bulunuyor…',
    'gc.locDenied': 'Konum izni verilmedi.',
    'gc.locFailed': 'Şehir bulunamadı.',
    // ── Mesajlar ──
    'msg.title': 'Mesajlar',
    'gif.search': 'GIF ara',
    'gif.empty': 'Sonuç bulunamadı.',
    'gif.disabled': 'GIF gönderimi şu an kapalı.',
    'msg.gif': 'GIF',
    'msg.pin': 'Sabitle',
    'msg.unpin': 'Sabitlemeyi kaldır',
    'msg.pinned': 'Sabitlenmiş mesaj',
    'msg.pinFailed': 'Sabitlenemedi.',
    'msg.reply': 'Yanıtla',
    'msg.replyToSelf': 'Sen',
    'msg.quoteMissing': 'Mesaj bulunamadı',
    'msg.copy': 'Kopyala',
    'msg.reportMessage': 'Şikayet et',
    // ── Doğrulanmış incelemeler ──
    'rev.section': 'Topluluk incelemeleri',
    'rev.canWrite': 'Yazabileceğin oyunlar',
    'rev.community': 'Topluluk',
    'rev.mine': 'Benimkiler',
    'rev.communityEmpty': 'Henüz inceleme yok. İlk yazan sen ol — kütüphanendeki oyunlardan birini seç.',
    'rev.mineEmpty': 'Henüz inceleme yazmadın.',
    'rev.noEligible': 'İnceleme yazmak için Steam hesabını bağla ve en az 1 saat oynadığın bir oyunun olsun.',
    'prof.gReviews': 'İnceleme',
    'rev.recommendRate': 'öneriyor',
    'rev.verifiedReviews': 'doğrulanmış inceleme',
    'rev.write': 'İnceleme yaz',
    'rev.edit': 'İncelemeni düzenle',
    'rev.empty': 'Bu oyuna henüz inceleme yazılmamış. İlk sen ol.',
    'rev.placeholder': 'Bu oyun hakkında ne düşünüyorsun? Kaç saat oynadığın incelemenin yanında görünecek.',
    'rev.yes': 'Öneriyorum',
    'rev.no': 'Önermiyorum',
    'rev.save': 'Yayınla',
    'rev.delete': 'Sil',
    'rev.deleteTitle': 'İncelemeyi sil',
    'rev.deleteText': 'Bu inceleme kaldırılacak.',
    'rev.saveFailed': 'İnceleme kaydedilemedi',
    'rev.notInLibrary': 'Bu oyunu Steam kütüphanende bulamadık. İnceleme yazmak için oyunun sende olması ve Steam gizlilik ayarlarında oyun ayrıntılarının herkese açık olması gerekiyor.',
    'rev.notEnoughHours': 'İnceleme yazmak için bu oyunu en az 1 saat oynamış olman gerekiyor.',
    'set.language': 'Dil',
    'soc.showPresence': 'Çevrimiçi durumum',
    'soc.showPresenceDesc': 'Arkadaşların çevrimiçi olduğunu ve son görülme zamanını görebilir.',
    'msg.sharedReel': 'Video paylaştı',
    'share.title': 'Arkadaşa gönder',
    'share.send': 'Gönder',
    'share.sent': 'Gönderildi',
    'share.noFriends': 'Henüz arkadaşın yok. Önce arkadaş ekle.',
    'vid.share': 'Gönder',
    'msg.seen': 'Görüldü',
    'msg.sending': 'Gönderiliyor…',
    'msg.notSent': 'Gönderilemedi',
    'msg.online': 'çevrimiçi',
    'msg.typing': 'yazıyor…',
    'msg.lastSeen': 'son görülme',
    'msg.yesterday': 'dün',
    'msg.undo': 'Geri al',
    'msg.undoTitle': 'Mesajı geri al',
    'msg.undoText': 'Bu mesaj iki taraftan da kaldırılacak.',
    'msg.undoFailed': 'Mesaj geri alınamadı',
    'msg.wasUndone': 'Bu mesaj geri alındı',
    'msg.cancel': 'Vazgeç',
    'msg.photo': 'Fotoğraf',
    'msg.video': 'Video',
    'msg.videoTooLong': 'Video çok uzun veya çok büyük. 15 saniyeden kısa bir klip seç.',
    'msg.needPhotoPerm': 'Fotoğraf göndermek için galeri izni gerekiyor.',
    'msg.mediaOff': 'Fotoğraf gönderimi şu an kapalı.',
    'msg.videoOff': 'Video gönderimi henüz kapalı. Şimdilik fotoğraf gönderebilirsin.',
    'msg.mediaRejected': 'Bu görsel gönderilemez.',
    'msg.mediaTooBig': 'Görsel çok büyük.',
    'msg.empty': 'Henüz mesajın yok',
    'msg.emptyText': 'Sohbet etmek için önce arkadaş ekle, sonra listeden birine dokun.',
    'msg.goFriends': 'Arkadaşlara git',
    'msg.placeholder': 'Mesaj yaz…',
    'msg.startText': 'Sohbeti başlat.',
    'msg.notFriends': 'Arkadaş değilsiniz',
    'msg.notFriendsText': 'Mesajlaşmak için önce arkadaş olmanız gerekiyor.',
    'msg.blocked': 'Engellenmiş',
    'msg.blockedText': 'Bu kullanıcıyla mesajlaşamazsın.',
    'msg.sendFailed': 'Mesaj gönderilemedi',
    'msg.tooLong': 'Mesaj çok uzun',
    'msg.inappropriate': 'Bu mesaj gönderilemez',
    'gc.loading': 'Kütüphanen hesaplanıyor…',
    'gc.empty': 'Henüz kart yok',
    'gc.emptyText': 'Kart oluşması için Steam kütüphanende en az bir saat oynadığın bir oyun olmalı.',
    'gc.totalHours': 'toplam saat',
    'gc.games': 'oyun',
    'gc.untouched': 'hiç açılmamış',
    'gc.friends': 'arkadaş',
    'gc.among': 'arkadaşların arasında',
    'gc.hoursShort': 's',
    'gc.shareFailed': 'Paylaşım açılamadı',
    'sf.friends': 'arkadaş',
    'sf.hidden': 'gizli profil',
    'sf.loading': 'Steam kütüphaneleri karşılaştırılıyor…',
    'sf.needAccount': 'Önce giriş yap',
    'sf.needAccountText': 'Steam arkadaşlarını görmek için Gamerisen hesabın gerekiyor.',
    'sf.goAccount': 'Hesabıma git',
    'sf.noSteam': 'Steam bağlı değil',
    'sf.noSteamText': 'Arkadaşlarınla hangi oyunlara birlikte sahip olduğunu görmek için profilinden Steam hesabını bağla.',
    'sf.goProfile': 'Profile git',
    'sf.selfPrivate': 'Steam profilin gizli',
    'sf.selfPrivateText': 'Steam > Profili Düzenle > Gizlilik Ayarları bölümünden "Oyun ayrıntıları" seçeneğini herkese açık yap, sonra listeyi yenile.',
    'sf.error': 'Bağlanamadık',
    'sf.errorText': 'Steam şu an yanıt vermiyor olabilir. Birazdan tekrar dene.',
    'sf.retry': 'Tekrar dene',
    'sf.empty': 'Arkadaş görünmüyor',
    'sf.emptyText': 'Steam arkadaş listen boş olabilir ya da gizlilik ayarlarında "Arkadaş listesi" herkese açık değildir.',
    'sf.rowPrivate': 'Kütüphanesi gizli',
    'sf.together': 'birlikte oynanır',
    'sf.shared': 'ortak',
    'soc.title': 'Arkadaşlar',
    'soc.tabFeed': 'Akış',
    'soc.tabFriends': 'Arkadaşlar',
    'soc.tabRequests': 'İstekler',
    'soc.setupTitle': 'Sosyal profilini oluştur',
    'soc.setupText': 'Arkadaşlarını bulabilmen ve seni bulabilmeleri için bir kullanıcı adı seç.',
    'soc.usernameLabel': 'Kullanıcı adı',
    'soc.usernamePlaceholder': 'kullanici_adi',
    'soc.usernameHint': '3-20 karakter · harf, rakam ve alt çizgi',
    'soc.checking': 'Kontrol ediliyor…',
    'soc.available': 'Bu ad uygun',
    'soc.create': 'Devam et',
    'soc.privacyNote': 'Aktiviteni yalnızca arkadaşların görür. Bunu istediğin an ayarlardan kapatabilirsin.',
    'soc.needSession': 'Bu özellik için hesabınla giriş yapmalısın.',
    'soc.signIn': 'Giriş yap',
    'soc.searchPlaceholder': 'Kullanıcı adı ara…',
    'soc.searchHint': 'Arkadaşını bulmak için kullanıcı adının en az 2 harfini yaz.',
    'soc.noResults': 'Kullanıcı bulunamadı',
    'soc.add': 'Ekle',
    'soc.requested': 'İstek gönderildi',
    'soc.accept': 'Kabul et',
    'soc.reject': 'Reddet',
    'soc.friends': 'Arkadaşsınız',
    'soc.remove': 'Arkadaşlıktan çıkar',
    'soc.removeConfirm': 'Bu kişiyi arkadaşlıktan çıkarmak istiyor musun?',
    'soc.noFriends': 'Henüz arkadaşın yok',
    'soc.noFriendsText': 'Kullanıcı adıyla arayarak arkadaş ekleyebilirsin.',
    'soc.noRequests': 'Bekleyen istek yok',
    'soc.incoming': 'Gelen istekler',
    'soc.outgoing': 'Gönderdiklerin',
    'soc.cancel': 'İptal et',
    'soc.emptyFeed': 'Akış henüz boş',
    'soc.emptyFeedText': 'Arkadaşların oyun kaydettikçe burada göreceksin.',
    'soc.actWishlist': 'takibe aldı',
    'soc.actCollection': 'koleksiyonuna ekledi',
    'soc.actLike': 'beğendi',
    'soc.actFinished': 'bitirdi',
    'soc.block': 'Engelle',
    'soc.blockConfirm': 'Bu kişi seni göremez, sen de onu göremezsin. Arkadaşsanız arkadaşlık kalkar.',
    'soc.unblock': 'Engeli kaldır',
    'soc.blocked': 'Engellenenler',
    'soc.noBlocked': 'Engellenen kimse yok',
    'soc.report': 'Şikayet et',
    'soc.reportTitle': 'Neyi şikayet ediyorsun?',
    'soc.reportSent': 'Şikayetin alındı. En kısa sürede inceleyeceğiz.',
    'soc.reportNote': 'Eklemek istediğin bir şey var mı? (isteğe bağlı)',
    'soc.reportSubmit': 'Şikayeti gönder',
    'soc.reason.spam': 'Spam veya reklam',
    'soc.reason.harassment': 'Taciz veya zorbalık',
    'soc.reason.hate': 'Nefret söylemi',
    'soc.reason.sexual': 'Cinsel içerik',
    'soc.reason.violence': 'Şiddet',
    'soc.reason.impersonation': 'Kimlik taklidi',
    'soc.reason.illegal': 'Yasa dışı içerik',
    'soc.reason.other': 'Diğer',
    'soc.privacyTitle': 'Sosyal gizlilik',
    'soc.shareActivity': 'Aktivitemi arkadaşlarım görsün',
    'soc.discoverable': 'Kullanıcı adımla bulunabileyim',
    'soc.err.USERNAME_FORMAT': '3-20 karakter, yalnızca harf, rakam ve alt çizgi',
    'soc.err.USERNAME_RESERVED': 'Bu ad kullanılamaz',
    'soc.err.USERNAME_INAPPROPRIATE': 'Bu ad uygun değil',
    'soc.err.TAKEN': 'Bu ad alınmış',
    'soc.err.RATE_LIMITED': 'Çok fazla deneme. Biraz bekle.',
    'soc.err.generic': 'Bir şeyler ters gitti. Tekrar dene.',
    'soc.timeNow': 'şimdi',
    'soc.timeMin': 'dk',
    'soc.timeHour': 'sa',
    'soc.timeDay': 'g',
    // ── Topluluk listeleri ──
    'pl.entry': 'Topluluk listeleri',
    'pl.title': 'Topluluk Listeleri',
    'pl.sortPopular': 'Popüler',
    'pl.sortNew': 'Yeni',
    'pl.empty': 'Henüz liste yok',
    'pl.emptyText': 'İlk listeyi sen yayınla — koleksiyonlarından birini paylaşabilirsin.',
    'pl.games': 'oyun',
    'pl.official': 'EDİTÖR',
    'pl.by': 'hazırlayan',
    'pl.publish': 'Toplulukla paylaş',
    'pl.publishTitle': 'Listeyi yayınla',
    'pl.publishText': 'Bu koleksiyon herkese açık olur; kullanıcı adınla birlikte görünür.',
    'pl.listTitle': 'Liste başlığı',
    'pl.listDesc': 'Kısa açıklama (isteğe bağlı)',
    'pl.publishBtn': 'Yayınla',
    'pl.update': 'Güncelle',
    'pl.published': 'Listen yayınlandı',
    'pl.unpublish': 'Yayından kaldır',
    'pl.unpublishConfirm': 'Liste topluluktan kaldırılsın mı? Kendi koleksiyonun silinmez.',
    'pl.cancel': 'Vazgeç',
    'pl.hiddenNotice': 'Bu liste şikayetler nedeniyle incelemede. Yalnızca sen görebiliyorsun.',
    'pl.mine': 'Yayınladıklarım',
    'pl.emptyList': 'Bu listede oyun yok',
    'pl.err.LIST_LIMIT': 'En fazla 20 liste yayınlayabilirsin',
    'pl.err.LIST_EMPTY': 'Boş koleksiyon yayınlanamaz',
    'pl.err.TEXT_INAPPROPRIATE': 'Bu metin uygun değil',
    'pl.err.TEXT_TOO_LONG': 'Metin çok uzun',
    'pl.err.TEXT_EMPTY': 'Başlık gerekli',
    // ── Profil / Ayarlar ayrımı ──
    'prof.myContent': 'İçeriğim',
    'prof.gCollections': 'Koleksiyon',
    'prof.gWishlist': 'İstek',
    'prof.gLibrary': 'Kütüphane',
    'prof.gStats': 'Rapor',
    'prof.gCards': 'Kartlar',
    'prof.gDiscover': 'Keşfet',    'prof.gMessages': 'Mesaj',
    'prof.gSteam': 'Steam',
    'prof.gLists': 'Liste',
    'prof.yours': 'Senin',
    'prof.social': 'Sosyal',
    'prof.myGames': 'Oyunlarım',
    'prof.statCollections': 'koleksiyon',
    'prof.statFriends': 'arkadaş',
    'prof.statWishlist': 'takipte',
    'prof.statGames': 'oyun',
    'prof.noUsername': 'Kullanıcı adı belirle',
    'prof.chooseAvatar': 'Avatarını seç',
    'prof.removeAvatar': 'Kaldır',
    'prof.avatarSaved': 'Avatar güncellendi',
    'prof.avatarTap': 'Değiştirmek için dokun',
    'prof.connectHint': 'Kütüphaneni ve haftalık raporunu görmek için bir mağaza bağla.',
    'post.more': 'devamını gör',
    'vid.play': 'Oynat',
    'vid.landscape': 'Yatay moda geç',
    'vid.portrait': 'Dikey moda dön',
    'vid.pause': 'Duraklat',
    'post.less': 'daha az göster',
    'post.detail': 'Oyun sayfasına git',
    'prof.lockTitle': 'Profil oluşturun',
    'prof.lockDesc': 'Koleksiyonlarınız, istek listeniz ve bağladığınız Steam/Xbox hesapları profilinize kaydedilir — cihaz değiştirseniz de kaybolmaz.',
    'prof.lockCta': 'Profil oluştur',
    'prof.lockedHint': 'Profil oluşturunca açılır',
    'prof.settingsTitle': 'Ayarlar',
    'prof.settingsEntry': 'Ayarlar',
    'prof.general': 'Genel',
    'prof.privacy': 'Gizlilik',
    'prof.account': 'Hesap',
    'prof.language': 'Dil',
    // ── Erişilebilirlik etiketleri (VoiceOver) ──
    'a11y.back': 'Geri',
    'a11y.forward': 'İleri',
    'a11y.close': 'Kapat',
    'a11y.clear': 'Temizle',
    'a11y.delete': 'Sil',
    'a11y.share': 'Paylaş',
    'a11y.settings': 'Ayarlar',
    'a11y.rename': 'Yeniden adlandır',
    'a11y.add': 'Ekle',
    'a11y.addToCollection': 'Koleksiyona ekle',
    'a11y.follow': 'Takibe al',
    'a11y.unfollow': 'Takibi bırak',
    'a11y.report': 'Şikayet et',
    'a11y.more': 'Daha fazla',
    'a11y.undo': 'Geri al',
    'a11y.info': 'Bilgi',
    'a11y.like': 'Beğen',
    'a11y.confirm': 'Onayla',
    'a11y.search': 'Ara',
    'a11y.signOut': 'Çıkış yap',
    'discover.title': 'Ne arıyorsun?',
    'discover.subtitle': 'Aradığın oyunu kendi cümlelerinle anlat — türü, hissi, benzediği oyunu yaz.',
    'discover.placeholder': 'Örn: Dying Light gibi hikayeli ve arkadaşımla oynayabileceğim bir oyun',
    'discover.button': 'Oyun bul',
    'discover.searching': 'Aranıyor…',
    'discover.understood': 'Anladığım',
    'discover.empty': 'Bu tarife uygun oyun bulunamadı. Biraz daha farklı anlatmayı dene.',
    'discover.error': 'Arama şu an yapılamadı. Lütfen tekrar dene.',
    'discover.entry': 'Nasıl bir oyun istediğini anlat',
    'home.notInterested': 'İlgilenmiyorum',
    'home.dismissPrompt': 'Bu oyun önerilerden kaldırılsın mı?',
    'common.cancel': 'İptal',
    'library.soon': 'Kütüphane yakında mobilde',
    'profile.soon': 'Profil yakında mobilde',
    'auth.accounts': 'Bağlı Hesaplar',
    'auth.err.ACCOUNT_REQUIRED': 'Mağaza bağlamak için önce Gamerisen hesabına giriş yapın.',
    'auth.err.STEAM_LIMIT': 'En fazla 5 Steam hesabı bağlayabilirsiniz.',
    'auth.err.SYNC_FAILED': 'Bağlantı hesabınıza kaydedilemedi. Bağlantınızı kontrolüp tekrar deneyin.',
    'auth.connectSteam': 'Steam ile Bağlan',
    'auth.connectXbox': 'Xbox ile Bağlan',
    'auth.addSteam': '+ Steam Hesabı Ekle',
    'auth.connected': 'Bağlı',
    'auth.disconnect': 'Çıkış',
    'auth.loginFailed': 'Giriş başarısız oldu',
    'auth.games': 'oyun',
    'library.connectPrompt': 'Oyunlarını görmek için Steam veya Xbox hesabını bağla.',
    'library.hoursPlayed': 'saat oynandı',
    'library.notPlayed': 'Oynanmadı',
    'lib.overview': 'Genel',
    'lib.accounts': 'hesap',
    'lib.games': 'Oyun',
    'lib.played': 'Oynanan',
    'lib.hours': 'Saat',
    'lib.value': 'Değer',
    'lib.gamerscore': 'Gamerscore',
    'lib.search': 'Kütüphanede ara…',
    'lib.sortHours': 'Saat',
    'lib.sortName': 'İsim',
    'lib.sortValue': 'Değer',
    'lib.empty': 'Bu filtreyle oyun yok',
    'common.loading': 'Yükleniyor…',
    'common.retry': 'Tekrar dene',
    'common.back': 'Geri',
    'notif.title': 'İndirim Uyarıları',
    'notif.desc': 'Takip ettiğin oyunlar indirime girince bildirim al.',
    'notif.enable': 'Bildirimleri Aç',
    'notif.enabled': 'Bildirimler açık',
    'notif.permissionError': 'Bildirim izni verilmedi',
    'notif.needDevBuild': 'Push bildirimleri Expo Go\'da çalışmaz; geliştirme veya mağaza sürümü gerekir.',
    'wishlist.title': 'İstek Listesi',
    'wishlist.empty': 'Henüz oyun eklemedin',
    'wishlist.emptyDesc': 'Oyun detayında 🔔 ile takip et; indirime girince haber ver.',
    'wishlist.add': 'İndirim uyarısı ekle',
    'wishlist.added': 'İzleniyor',
    'wishlist.count': 'oyun izleniyor',
    'wishlist.explore': 'Oyun Keşfet',
    'detail.about': 'Hakkında',
    'detail.screenshots': 'Ekran Görüntüleri',
    'detail.genres': 'Türler',
    'detail.stores': 'Mağazalar',
    'detail.developer': 'Geliştirici',
    'detail.released': 'Çıkış',
    'detail.more': 'Devamını oku',
    'detail.less': 'Daha az',
    'detail.official': 'Resmi Site',
    'detail.priceCompare': 'Fiyat Karşılaştırması',
    'detail.cheapest': 'En ucuz',
    'detail.reviews': 'Değerlendirmeler',
    'detail.positive': 'olumlu',
    'detail.reviewsCount': 'inceleme',
    'review.veryPositive': 'Çok Olumlu',
    'review.positive': 'Olumlu',
    'review.mostlyPositive': 'Çoğunlukla Olumlu',
    'review.mixed': 'Karışık',
    'review.negative': 'Olumsuz',
  },
  en: {
    'nav.home': 'Home',
    'home.reviewPrompt': 'You played these — what did you think?',
    'home.friendsPlaying': 'Your friends this week',
    'nav.games': 'Games',
    'nav.news': 'News',
    'nav.videos': 'Videos',
    'nav.library': 'Library',
    'nav.profile': 'Profile',
    'nav.messages': 'Messages',
    'news.title': 'News',
    'news.all': 'All',
    'news.empty': 'No news found',
    'news.featured': 'FEATURED',
    'games.title': 'Games',
    'games.searchPlaceholder': 'Search games…',
    'games.noResults': 'No results found',
    'games.loading': 'Loading…',
    'card.free': 'Free',
    'section.all': 'All',
    'section.popular': 'Popular',
    'section.new': 'New',
    'section.sale': 'On Sale',
    'section.free': 'Free',
    'section.topscore': 'Top Rated',
    'mode.all': 'All Modes',
    'mode.singleplayer': 'Single-player',
    'mode.multiplayer': 'Multiplayer',
    'mode.coop': 'Co-op',
    'home.tagline': 'Discover PC games, compare prices, connect your library.',
    'home.exploreGames': 'Explore Games',
    'hero.badge': 'Live price comparison',
    'hero.subtitle': 'Picks based on your taste — compare Steam, Epic, GOG and Humble prices on one screen',
    'hero.search': 'Search games…',
    'home.forYou': 'For You',
    'home.trend': 'Trending This Week',
    'home.new': 'New Releases',
    'home.sale': 'On Sale',
    'home.viewAll': 'All',
    'acc.or': 'or',
    'acc.appleReauth': 'Re-authenticate with Apple to confirm deletion',
    'acc.appleReauthBtn': 'Verify with Apple and delete',
    'acc.signIn': 'Sign in',
    'acc.signUp': 'Create account',
    'acc.name': 'Your name',
    'acc.email': 'Email',
    'acc.password': 'Password',
    'acc.haveAccount': 'Already have an account? Sign in',
    'acc.noAccount': "Don't have an account? Create one",
    'acc.forgot': 'Forgot password',
    'acc.signOut': 'Sign out',
    'acc.signedInAs': 'Signed in',
    'acc.why': 'With an account, your taste profile and wishlist stay the same on every device.',
    'acc.transferTitle': 'Data on this device',
    'acc.transferBody': 'Transfer {n} created while signed out to this account?',
    'acc.transferCollections': '{n} collections',
    'acc.transferWishlist': '{n} wishlist items',
    'acc.transferYes': 'Transfer',
    'acc.transferNo': "Don't transfer",
    'acc.verifySent': 'Verification email sent. Confirm your address, then sign in.',
    'acc.resetSent': 'A password reset link has been sent to your email.',
    'acc.notVerified': 'Your email is not verified yet. Please check your inbox.',
    'acc.deleteTitle': 'Delete account',
    'acc.deleteWarn': 'Your account and server-side data will be permanently deleted. This cannot be undone.',
    'acc.deleteConfirm': 'Permanently delete my account',
    'acc.emailRequired': 'Please enter your email address.',
    'acc.passwordRequired': 'Please enter your password.',
    'acc.passwordTooShort': 'Password must be at least 6 characters.',
    'acc.nameRequired': 'Please enter your name.',
    'acc.sendResetLink': 'Send Reset Link',
    'acc.backToSignIn': 'Back to Sign In',
    'onb.title': 'Which ones do you like?',
    'onb.subtitle': 'Pick a few games and we will tailor your recommendations right away.',
    'onb.selected': 'selected',
    'onb.need': 'Pick at least 3 games',
    'onb.continue': 'Continue',
    'onb.skip': 'Skip for now',
    'onb.retake': 'Redo your taste picks',
    'onb.done': 'Your taste has been updated',
    'swipe.title': 'Discover',
    'swipe.subtitle': 'Swipe right if it interests you · left if it does not',
    'swipe.like': 'INTERESTED',
    'swipe.pass': 'NOT FOR ME',
    'swipe.liked': 'liked',
    'swipe.passed': 'passed',
    'swipe.emptyTitle': 'That is all for now',
    'swipe.emptyText': 'New games will show up here as they arrive. Your picks are already shaping your recommendations.',
    'swipe.entry': 'Discover by swiping',
    'col.title': 'My Collections',
    'col.entry': 'My Collections',
    'col.empty': 'No collections yet',
    'col.emptyText': 'Group games into your own lists: finished, favourites, co-op nights…',
    'col.new': 'New collection',
    'col.create': 'Create',
    'col.cancel': 'Cancel',
    'col.namePlaceholder': 'Collection name',
    'col.rename': 'Rename',
    'col.save': 'Save',
    'col.delete': 'Delete collection',
    'col.deleteConfirm': 'Delete this collection? The games stay, only the list is removed.',
    'col.gameCount': 'games',
    'col.emptyList': 'This collection is empty',
    'col.emptyListText': 'You can add games from any game detail page.',
    'col.addTo': 'Add to collection',
    'col.added': 'Added',
    'col.removeGame': 'Remove from list',
    'col.limitReached': 'You can create up to 50 collections',
    'col.suggest1': 'Games I Finished',
    'col.suggest2': 'My 2026 Favourites',
    'col.suggest3': 'Co-op Games',
    'vid.title': 'Game Videos',
    'vid.entry': 'Game videos',
    'vid.loading': 'Preparing videos…',
    'vid.follow': 'Follow',
    'vid.save': 'Save',
    'vid.buy': 'Buy',
    'vid.mute': 'Mute',
    'vid.unmute': 'Unmute',
    'vid.detail': 'Go to game detail',
    'stats.title': 'Your Week',
    'stats.entry': 'Your weekly report',
    'stats.subtitle': 'What you did in the last 7 days',
    'stats.discovered': 'games discovered',
    'stats.liked': 'games liked',
    'stats.passed': 'games passed',
    'stats.wishlist': 'games followed',
    'stats.collections': 'collections',
    'stats.collected': 'games in your lists',
    'stats.topGenre': 'Genre you explored most',
    'stats.avgDiscount': 'Average discount in your list',
    'stats.bestDiscount': 'Best discount',
    'stats.onSale': 'games on sale',
    'stats.genreTitle': 'Your genre mix',
    'stats.emptyTitle': 'Nothing to show yet',
    'stats.emptyText': 'Discover some games, swipe and build lists — your weekly report will appear here.',
    'stats.startBrowsing': 'Browse games',
    'stats.startSwiping': 'Start swiping',
    'stats.share': 'Share',
    'stats.decisions': 'decisions made',
    // ── Social ──
    'soc.entry': 'Friends',
    // ── Steam friends ──
    'sf.title': 'Your Steam Friends',
    // ── Game cards ──
    'gc.title': 'Your Game Cards',
    'gc.addCity': 'Add my city to the card',
    'gc.locOff': 'Off — no location shared',
    'gc.locResolving': 'Finding city…',
    'gc.locDenied': 'Location permission denied.',
    'gc.locFailed': 'Could not determine city.',
    // ── Messages ──
    'msg.title': 'Messages',
    'gif.search': 'Search GIFs',
    'gif.empty': 'No results.',
    'gif.disabled': 'GIF sending is currently disabled.',
    'msg.gif': 'GIF',
    'msg.pin': 'Pin',
    'msg.unpin': 'Unpin',
    'msg.pinned': 'Pinned message',
    'msg.pinFailed': 'Could not pin.',
    'msg.reply': 'Reply',
    'msg.replyToSelf': 'You',
    'msg.quoteMissing': 'Message unavailable',
    'msg.copy': 'Copy',
    'msg.reportMessage': 'Report',
    // ── Verified reviews ──
    'rev.section': 'Community reviews',
    'rev.canWrite': 'Games you can review',
    'rev.community': 'Community',
    'rev.mine': 'Yours',
    'rev.communityEmpty': 'No reviews yet. Be the first — pick a game from your library.',
    'rev.mineEmpty': 'You have not written a review yet.',
    'rev.noEligible': 'Connect your Steam account and play a game for at least an hour to write a review.',
    'prof.gReviews': 'Reviews',
    'rev.recommendRate': 'recommend it',
    'rev.verifiedReviews': 'verified reviews',
    'rev.write': 'Write a review',
    'rev.edit': 'Edit your review',
    'rev.empty': 'No reviews yet. Be the first.',
    'rev.placeholder': 'What do you think about this game? Your playtime will be shown next to your review.',
    'rev.yes': 'Recommend',
    'rev.no': 'Do not recommend',
    'rev.save': 'Publish',
    'rev.delete': 'Delete',
    'rev.deleteTitle': 'Delete review',
    'rev.deleteText': 'This review will be removed.',
    'rev.saveFailed': 'Could not save review',
    'rev.notInLibrary': 'We could not find this game in your Steam library. To write a review you need to own the game and have game details set to public in your Steam privacy settings.',
    'rev.notEnoughHours': 'You need at least 1 hour of playtime in this game to write a review.',
    'set.language': 'Language',
    'soc.showPresence': 'Online status',
    'soc.showPresenceDesc': 'Friends can see when you are online and your last seen time.',
    'msg.sharedReel': 'Shared a video',
    'share.title': 'Send to a friend',
    'share.send': 'Send',
    'share.sent': 'Sent',
    'share.noFriends': 'No friends yet. Add someone first.',
    'vid.share': 'Send',
    'msg.seen': 'Seen',
    'msg.sending': 'Sending…',
    'msg.notSent': 'Not sent',
    'msg.online': 'online',
    'msg.typing': 'typing…',
    'msg.lastSeen': 'last seen',
    'msg.yesterday': 'yesterday',
    'msg.undo': 'Unsend',
    'msg.undoTitle': 'Unsend message',
    'msg.undoText': 'This message will be removed for both of you.',
    'msg.undoFailed': 'Could not unsend message',
    'msg.wasUndone': 'This message was unsent',
    'msg.cancel': 'Cancel',
    'msg.photo': 'Photo',
    'msg.video': 'Video',
    'msg.videoTooLong': 'Video is too long or too large. Pick a clip under 15 seconds.',
    'msg.needPhotoPerm': 'Photo library access is required to send images.',
    'msg.mediaOff': 'Photo sending is currently disabled.',
    'msg.videoOff': 'Video sending is not available yet. You can send photos for now.',
    'msg.mediaRejected': 'This image cannot be sent.',
    'msg.mediaTooBig': 'Image is too large.',
    'msg.empty': 'No messages yet',
    'msg.emptyText': 'Add friends first, then tap someone in the list to start chatting.',
    'msg.goFriends': 'Go to friends',
    'msg.placeholder': 'Write a message…',
    'msg.startText': 'Start the conversation.',
    'msg.notFriends': 'Not friends',
    'msg.notFriendsText': 'You need to be friends to exchange messages.',
    'msg.blocked': 'Blocked',
    'msg.blockedText': 'You cannot message this user.',
    'msg.sendFailed': 'Could not send message',
    'msg.tooLong': 'Message is too long',
    'msg.inappropriate': 'This message cannot be sent',
    'gc.loading': 'Crunching your library…',
    'gc.empty': 'No cards yet',
    'gc.emptyText': 'You need at least one game with an hour of playtime in your Steam library.',
    'gc.totalHours': 'total hours',
    'gc.games': 'games',
    'gc.untouched': 'never opened',
    'gc.friends': 'friends',
    'gc.among': 'among friends',
    'gc.hoursShort': 'h',
    'gc.shareFailed': 'Could not open share sheet',
    'sf.friends': 'friends',
    'sf.hidden': 'private',
    'sf.loading': 'Comparing Steam libraries…',
    'sf.needAccount': 'Sign in first',
    'sf.needAccountText': 'You need a Gamerisen account to see your Steam friends.',
    'sf.goAccount': 'Go to account',
    'sf.noSteam': 'Steam not connected',
    'sf.noSteamText': 'Connect your Steam account from your profile to see which games you own together with friends.',
    'sf.goProfile': 'Go to profile',
    'sf.selfPrivate': 'Your Steam profile is private',
    'sf.selfPrivateText': 'In Steam > Edit Profile > Privacy Settings, set "Game details" to Public, then refresh the list.',
    'sf.error': 'Could not connect',
    'sf.errorText': 'Steam may not be responding right now. Try again shortly.',
    'sf.retry': 'Try again',
    'sf.empty': 'No friends found',
    'sf.emptyText': 'Your Steam friend list may be empty, or "Friends list" is not public in your privacy settings.',
    'sf.rowPrivate': 'Library is private',
    'sf.together': 'playable together',
    'sf.shared': 'shared',
    'soc.title': 'Friends',
    'soc.tabFeed': 'Feed',
    'soc.tabFriends': 'Friends',
    'soc.tabRequests': 'Requests',
    'soc.setupTitle': 'Create your social profile',
    'soc.setupText': 'Pick a username so you can find friends and they can find you.',
    'soc.usernameLabel': 'Username',
    'soc.usernamePlaceholder': 'your_username',
    'soc.usernameHint': '3-20 characters · letters, numbers and underscore',
    'soc.checking': 'Checking…',
    'soc.available': 'This name is available',
    'soc.create': 'Continue',
    'soc.privacyNote': 'Only your friends can see your activity. You can turn this off any time in settings.',
    'soc.needSession': 'Sign in to your account to use this feature.',
    'soc.signIn': 'Sign in',
    'soc.searchPlaceholder': 'Search username…',
    'soc.searchHint': 'Type at least 2 letters of a username to find a friend.',
    'soc.noResults': 'No users found',
    'soc.add': 'Add',
    'soc.requested': 'Request sent',
    'soc.accept': 'Accept',
    'soc.reject': 'Decline',
    'soc.friends': 'Friends',
    'soc.remove': 'Remove friend',
    'soc.removeConfirm': 'Remove this person from your friends?',
    'soc.noFriends': 'No friends yet',
    'soc.noFriendsText': 'Search by username to add friends.',
    'soc.noRequests': 'No pending requests',
    'soc.incoming': 'Incoming',
    'soc.outgoing': 'Sent',
    'soc.cancel': 'Cancel',
    'soc.emptyFeed': 'Your feed is empty',
    'soc.emptyFeedText': "You'll see it here as your friends save games.",
    'soc.actWishlist': 'started following',
    'soc.actCollection': 'added to a collection',
    'soc.actLike': 'liked',
    'soc.actFinished': 'finished',
    'soc.block': 'Block',
    'soc.blockConfirm': "They won't see you and you won't see them. If you are friends, the friendship is removed.",
    'soc.unblock': 'Unblock',
    'soc.blocked': 'Blocked users',
    'soc.noBlocked': 'No blocked users',
    'soc.report': 'Report',
    'soc.reportTitle': 'What are you reporting?',
    'soc.reportSent': 'Report received. We will review it shortly.',
    'soc.reportNote': 'Anything you want to add? (optional)',
    'soc.reportSubmit': 'Submit report',
    'soc.reason.spam': 'Spam or advertising',
    'soc.reason.harassment': 'Harassment or bullying',
    'soc.reason.hate': 'Hate speech',
    'soc.reason.sexual': 'Sexual content',
    'soc.reason.violence': 'Violence',
    'soc.reason.impersonation': 'Impersonation',
    'soc.reason.illegal': 'Illegal content',
    'soc.reason.other': 'Other',
    'soc.privacyTitle': 'Social privacy',
    'soc.shareActivity': 'Let friends see my activity',
    'soc.discoverable': 'Let people find me by username',
    'soc.err.USERNAME_FORMAT': '3-20 characters, letters, numbers and underscore only',
    'soc.err.USERNAME_RESERVED': 'This name cannot be used',
    'soc.err.USERNAME_INAPPROPRIATE': 'This name is not appropriate',
    'soc.err.TAKEN': 'This name is taken',
    'soc.err.RATE_LIMITED': 'Too many attempts. Please wait.',
    'soc.err.generic': 'Something went wrong. Try again.',
    'soc.timeNow': 'now',
    'soc.timeMin': 'm',
    'soc.timeHour': 'h',
    'soc.timeDay': 'd',
    // ── Community lists ──
    'pl.entry': 'Community lists',
    'pl.title': 'Community Lists',
    'pl.sortPopular': 'Popular',
    'pl.sortNew': 'New',
    'pl.empty': 'No lists yet',
    'pl.emptyText': 'Be the first to publish one — share any of your collections.',
    'pl.games': 'games',
    'pl.official': 'EDITORS',
    'pl.by': 'by',
    'pl.publish': 'Share with community',
    'pl.publishTitle': 'Publish list',
    'pl.publishText': 'This collection becomes public and appears with your username.',
    'pl.listTitle': 'List title',
    'pl.listDesc': 'Short description (optional)',
    'pl.publishBtn': 'Publish',
    'pl.update': 'Update',
    'pl.published': 'Your list is live',
    'pl.unpublish': 'Unpublish',
    'pl.unpublishConfirm': 'Remove this list from the community? Your own collection stays.',
    'pl.cancel': 'Cancel',
    'pl.hiddenNotice': 'This list is under review after reports. Only you can see it.',
    'pl.mine': 'Published by me',
    'pl.emptyList': 'This list has no games',
    'pl.err.LIST_LIMIT': 'You can publish up to 20 lists',
    'pl.err.LIST_EMPTY': 'An empty collection cannot be published',
    'pl.err.TEXT_INAPPROPRIATE': 'This text is not appropriate',
    'pl.err.TEXT_TOO_LONG': 'Text is too long',
    'pl.err.TEXT_EMPTY': 'A title is required',
    // ── Profile / Settings split ──
    'prof.myContent': 'My content',
    'prof.gCollections': 'Collections',
    'prof.gWishlist': 'Wishlist',
    'prof.gLibrary': 'Library',
    'prof.gStats': 'Report',
    'prof.gCards': 'Cards',
    'prof.gDiscover': 'Discover',    'prof.gMessages': 'Messages',
    'prof.gSteam': 'Steam',
    'prof.gLists': 'Lists',
    'prof.yours': 'Yours',
    'prof.social': 'Social',
    'prof.myGames': 'My games',
    'prof.statCollections': 'collections',
    'prof.statFriends': 'friends',
    'prof.statWishlist': 'following',
    'prof.statGames': 'games',
    'prof.noUsername': 'Set a username',
    'prof.chooseAvatar': 'Choose your avatar',
    'prof.removeAvatar': 'Remove',
    'prof.avatarSaved': 'Avatar updated',
    'prof.avatarTap': 'Tap to change',
    'prof.connectHint': 'Connect a store to see your library and weekly report.',
    'post.more': 'see more',
    'vid.play': 'Play',
    'vid.landscape': 'Switch to landscape',
    'vid.portrait': 'Back to portrait',
    'vid.pause': 'Pause',
    'post.less': 'show less',
    'post.detail': 'Open game page',
    'prof.lockTitle': 'Create a profile',
    'prof.lockDesc': 'Your collections, wishlist and linked Steam/Xbox accounts are saved to your profile — they survive a device change.',
    'prof.lockCta': 'Create profile',
    'prof.lockedHint': 'Unlocks after you create a profile',
    'prof.settingsTitle': 'Settings',
    'prof.settingsEntry': 'Settings',
    'prof.general': 'General',
    'prof.privacy': 'Privacy',
    'prof.account': 'Account',
    'prof.language': 'Language',
    // ── Accessibility labels (VoiceOver) ──
    'a11y.back': 'Back',
    'a11y.forward': 'Forward',
    'a11y.close': 'Close',
    'a11y.clear': 'Clear',
    'a11y.delete': 'Delete',
    'a11y.share': 'Share',
    'a11y.settings': 'Settings',
    'a11y.rename': 'Rename',
    'a11y.add': 'Add',
    'a11y.addToCollection': 'Add to collection',
    'a11y.follow': 'Follow',
    'a11y.unfollow': 'Unfollow',
    'a11y.report': 'Report',
    'a11y.more': 'More',
    'a11y.undo': 'Undo',
    'a11y.info': 'Info',
    'a11y.like': 'Like',
    'a11y.confirm': 'Confirm',
    'a11y.search': 'Search',
    'a11y.signOut': 'Sign out',
    'discover.title': 'What are you looking for?',
    'discover.subtitle': 'Describe the game in your own words — the genre, the feel, a game it resembles.',
    'discover.placeholder': 'e.g. A story-rich game like Dying Light that I can play with a friend',
    'discover.button': 'Find games',
    'discover.searching': 'Searching…',
    'discover.understood': 'What I understood',
    'discover.empty': 'No games matched that description. Try describing it a bit differently.',
    'discover.error': 'Search failed right now. Please try again.',
    'discover.entry': 'Describe the game you want',
    'home.notInterested': 'Not interested',
    'home.dismissPrompt': 'Remove this game from recommendations?',
    'common.cancel': 'Cancel',
    'library.soon': 'Library coming soon on mobile',
    'profile.soon': 'Profile coming soon on mobile',
    'auth.accounts': 'Connected Accounts',
    'auth.err.ACCOUNT_REQUIRED': 'Sign in to Gamerisen before connecting a store.',
    'auth.err.STEAM_LIMIT': 'You can connect at most 5 Steam accounts.',
    'auth.err.SYNC_FAILED': 'Could not save the connection to your account. Check your connection and try again.',
    'auth.connectSteam': 'Connect with Steam',
    'auth.connectXbox': 'Connect with Xbox',
    'auth.addSteam': '+ Add Steam Account',
    'auth.connected': 'Connected',
    'auth.disconnect': 'Disconnect',
    'auth.loginFailed': 'Login failed',
    'auth.games': 'games',
    'library.connectPrompt': 'Connect your Steam or Xbox account to see your games.',
    'library.hoursPlayed': 'hours played',
    'library.notPlayed': 'Not played',
    'lib.overview': 'Overview',
    'lib.accounts': 'accounts',
    'lib.games': 'Games',
    'lib.played': 'Played',
    'lib.hours': 'Hours',
    'lib.value': 'Value',
    'lib.gamerscore': 'Gamerscore',
    'lib.search': 'Search library…',
    'lib.sortHours': 'Hours',
    'lib.sortName': 'Name',
    'lib.sortValue': 'Value',
    'lib.empty': 'No games with this filter',
    'common.loading': 'Loading…',
    'common.retry': 'Retry',
    'common.back': 'Back',
    'notif.title': 'Discount Alerts',
    'notif.desc': 'Get notified when games you follow go on sale.',
    'notif.enable': 'Enable Notifications',
    'notif.enabled': 'Notifications on',
    'notif.permissionError': 'Notification permission denied',
    'notif.needDevBuild': 'Push notifications don\'t work in Expo Go; a dev or store build is required.',
    'wishlist.title': 'Wishlist',
    'wishlist.empty': 'No games added yet',
    'wishlist.emptyDesc': 'Follow a game with 🔔 on its detail page to get discount alerts.',
    'wishlist.add': 'Add discount alert',
    'wishlist.added': 'Watching',
    'wishlist.count': 'games watched',
    'wishlist.explore': 'Explore Games',
    'detail.about': 'About',
    'detail.screenshots': 'Screenshots',
    'detail.genres': 'Genres',
    'detail.stores': 'Stores',
    'detail.developer': 'Developer',
    'detail.released': 'Released',
    'detail.more': 'Read more',
    'detail.less': 'Show less',
    'detail.official': 'Official Site',
    'detail.priceCompare': 'Price Comparison',
    'detail.cheapest': 'Cheapest',
    'detail.reviews': 'Reviews',
    'detail.positive': 'positive',
    'detail.reviewsCount': 'reviews',
    'review.veryPositive': 'Very Positive',
    'review.positive': 'Positive',
    'review.mostlyPositive': 'Mostly Positive',
    'review.mixed': 'Mixed',
    'review.negative': 'Negative',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('tr');
  const [rate, setRate] = useState(38); // USD→TRY (web /api/usd-rate ile güncellenebilir)

  const t = useCallback((key) => STRINGS[lang][key] ?? STRINGS.en[key] ?? key, [lang]);

  // Web ile aynı biçim: TL için ₺ simgesi ve binlik ayraç
  const formatPrice = useCallback((priceTry) => {
    if (priceTry == null) return '';
    if (priceTry === 0) return t('card.free');
    if (lang === 'tr') {
      const val = Number(priceTry);
      const formatted = val % 1 === 0
        ? val.toLocaleString('tr-TR')
        : val.toLocaleString('tr-TR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
      return `${formatted}₺`;
    }
    return `$${(priceTry / (rate || 1)).toFixed(2)}`;
  }, [lang, rate, t]);

  const toggleLang = useCallback(() => setLang(l => (l === 'tr' ? 'en' : 'tr')), []);

  const value = useMemo(
    () => ({ lang, setLang, toggleLang, t, formatPrice, rate, setRate }),
    [lang, toggleLang, t, formatPrice, rate]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
